### ISSUE TITLE
zJunior is a website you can find all the interns available in the MENA Region

### ISSUE THREAD

**Issue by Mahmoudgalalz** [ACM-Alexandria-SC/Internships#86]
zJunior.com

it would be nice to corporate together

**Comment by karimkohel** [comment]
### Pro(grammer) move
I see you're a man of action @Mahmoudgalalz , you scraped all entries from the repo to use in zJunior and bragged about it on twitter (an elite programmer move by the way, I applaud the ingenuity). But the Idea about open sourcing is letting the community help itself, by letting the people keep this repo up to date then so it can self fulfill it's duty. So even if moving everything to a professional looking website (it definitely is btw good job, you and your team executed beautifully) how would you keep up with the constant updates. I'd love to brainstorm with you on how to go about automating that.

### For the the love of Open Source Community
In the end whatever works best would be the most popular solution, and that's again the beautiful thing about open sourcing. So if you really believe this is the way to go and have a clear vision of the value you and your team present to the community, then by all means tag me in, let me know if you'd want to talk more because i definitely do.

#### Collaborators and Contributors
I think the people who started this repo are awesome and would love for them to keep on the good work they're doing, this repo had a big impact on a lot of people that i have witnessed firsthand and would love for you guys to always look forward for expanding the outreach of your work.

### In the mean time
I'll keep helping and spreading this repo far and wide until i think there is a better way of helping the community so let's make a difference if we can and good luck if we don't get to collab on anything in the future.

**Comment by Mahmoudgalalz** [comment]
as you said, it's open-source I have a bit of people doesn't know what is ACM-Alex btw, and we are open-source too, having the same mission but bigger willing as we are trying really to help Juniors to have a real-world experience,
my tweets is my own

Github isn't your website to secure it, and we are both relying on scrapping data, zJunior of this repo
Just I used me way for that, 

and I have been a person who used this repo, all was I seek for more professional website hold a valid data

Also we are going to give up that way, we are kinda trying to do a real impact and it doesn't feel like we do, so as we are playing for that, we could sponsor this repo, in terms to stay updated under a maintaining team

**Comment by karimkohel** [comment]
@Mahmoudgalalz I don't think you got the heart of my message (it was entirely admiring your work, even the twitter part), my bet is that something was lost in translation.
And I'm not sure where your message leaves us.
So in effort to convey my message again i will summarize it here...

### Summary of my last message
- you've done a great job with zJunior (you and your team) it looks so cool
-  open source mean that the best idea and solution would always win (whatever it is and whom ever drives it)
- i did not shame any data scraping, on the contrary i admired it the act.
- i wanted to show support in your idea multiple times and would love to talk more about it

**Comment by Mahmoudgalalz** [comment]
Sorry for misunderstanding, I wasn't able to know the summary of the message, 
I would like to talk with you, and try to be beneficial for each other.

I like the competition, cuz it will make us do our best to win, otherwise I'm looking to talk more, I will dm you on twitter

to see how we can help each other

Thanks so much and I really appreciate your message

@karimkohel

**Comment by Mahmoudgalalz** [comment]
@MaiAhmedHussein could you give us your opinion about what @karimkohel said early, and How we can be beneficial?

**Comment by MaiAhmedHussein** [comment]
> @MaiAhmedHussein could you give us your opinion about what @karimkohel said early, and How we can be beneficial?

Hello @Mahmoudgalalz ,

Thank you for expressing your interest in collaborating with our repository. We appreciate your enthusiasm and would like to learn more about your specific goals and ideas for this collaboration.
To proceed further, could you please provide us with your LinkedIn account? This will allow us to connect with you and discuss the collaboration in more detail.
Additionally, we kindly request you to provide more details about what you specifically want to achieve through this collaboration.

Thank you,
ACM Technical Team

**Comment by Mahmoudgalalz** [comment]
Hello @MaiAhmedHussein 

https://linkedin.com/in/mahmoudgalalz

We are looking to sponsor ACM and collaborate on taking your data to our website, we have many planned work to help the community as you are trying to do, so we have been doing this work in a professional way, also we are collecting all opportunities for Juniors undergraduates, Fresh-grad, and we are willing to do more than that It would be great to have your name with us, as you are a place to rely on.
we could do an automation process that gives us your provided data on our website, I would like to work on this in collaboration with @karimkohel . 

I'm waiting for more info would be shared on a private channel as you mentioned "Linkedin"

**Comment by karimkohel** [comment]
I'd love to join the effort if you guys end up chatting, tag me along in a group chat. [here's my Linkedin too](https://linkedin.com/in/karimkohel) 

@Mahmoudgalalz @MaiAhmedHussein

**Comment by MaiAhmedHussein** [comment]
> I'd love to join the effort if you guys end up chatting, tag me along in a group chat. [here's my Linkedin too](https://linkedin.com/in/karimkohel)
> 
> @Mahmoudgalalz @MaiAhmedHussein

Sure 😃
